include:
  - path: ./docker-compose-base.yml

services:
  abacusflow-website:
    container_name: abacusflow--website
    image: brucewang5638/abacusflow-website:${ABACUSFLOW_WEBSITE_VERSION}
    networks:
      - abacusflow-network
    volumes:
      - /opt/acme-https/www:/var/www/certbot:ro
      - /opt/acme-https/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

  abacusflow-server:
    container_name: abacusflow-server
    image: brucewang5638/abacusflow-server:${ABACUSFLOW_SERVER_VERSION}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - abacusflow-network
    depends_on:
      - postgres
      - cube
    expose:
      - 8080
    ports:
      - "${ABACUSFLOW_SERVER_PORT}:8080"
  abacusflow-webapp:
    container_name: abacusflow-webapp
    image: brucewang5638/abacusflow-webapp:${ABACUSFLOW_WEBAPP_VERSION}
    environment:
      - ABACUSFLOW_SERVER_HOST=${ABACUSFLOW_SERVER_HOST}
      - ABACUSFLOW_SERVER_PORT=${ABACUSFLOW_SERVER_PORT}
      - ABACUSFLOW_CUBE_HOST=${ABACUSFLOW_CUBE_HOST}
      - ABACUSFLOW_CUBE_PORT=${ABACUSFLOW_CUBE_PORT}
    volumes:
      - /opt/acme-https/letsencrypt:/etc/letsencrypt:ro
    networks:
      - abacusflow-network
    depends_on:
      - abacusflow-server
    ports:
      - "${ABACUSFLOW_WEBAPP_PORT}:443"

