include:
  - path: ./docker-compose-base.yml

services:
  abacusflow-server:
    container_name: abacusflow-server
    image: ghcr.io/abacusflow/abacusflow-server:${ABACUSFLOW_SERVER_VERSION}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - abacusflow-network
    depends_on:
      - postgres
      - cube
    expose:
      - 8080
    ports:
      - "${ABACUSFLOW_SERVER_PORT}:8080"
  abacusflow-webapp:
    container_name: abacusflow-webapp
    image: ghcr.io/abacusflow/abacusflow-webapp:${ABACUSFLOW_WEBAPP_VERSION}
    environment:
      - REDIRECT_TO_HTTPS: "false"
      - ABACUSFLOW_SERVER_HOST=${ABACUSFLOW_SERVER_HOST}
      - ABACUSFLOW_SERVER_PORT=${ABACUSFLOW_SERVER_PORT}
      - ABACUSFLOW_CUBE_HOST=${ABACUSFLOW_CUBE_HOST}
      - ABACUSFLOW_CUBE_PORT=${ABACUSFLOW_CUBE_PORT}
    volumes:
      - /etc/letsencrypt/live/admin.abacusflow.cn/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/admin.abacusflow.cn/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    networks:
      - abacusflow-network
    depends_on:
      - abacusflow-server
    ports:
      - "${ABACUSFLOW_WEBAPP_HTTP_PORT}:80"
#      - "${ABACUSFLOW_WEBAPP_HTTPS_PORT}:443"

