cubes:
  - name: inventory
    sql_table: public.inventory
    data_source: default

    joins:
      - name: product
        sql: "{CUBE}.product_id = {product.id}"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: created_at
        sql: created_at
        type: time

      - name: updated_at
        sql: updated_at
        type: time

    measures:
      - name: count
        type: count

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

