cubes:
  - name: purchase_order_items
    sql_table: public.purchase_order_items
    data_source: default

    joins:
      - name: products
        sql: "{CUBE}.product_id = {products.id}"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: unit_price
        sql: unit_price
        type: string

      - name: product_type
        sql: product_type
        type: string

      - name: serial_number
        sql: serial_number
        type: string

    measures:
      - name: count
        type: count

      - name: quantity
        sql: quantity
        type: sum

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

