name: Init DB
description: Run SQL scripts to initialize DB
runs:
  using: composite
  steps:
    - name: Run initdb scripts
      run: |
        for file in "$GITHUB_WORKSPACE/script/initdb"/*.sql; do
          echo "→ running $file"
          psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB" \
              -v ON_ERROR_STOP=1 \
              -f "$file"
        done

