spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:abacusflow}
    username: ${POSTGRES_USER:abacusflow}
    password: ${POSTGRES_PASSWORD:123ABCdef*}
    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    file: UTF-8
    console: UTF-8
  file:
    name: logs/app.log