services:
  acme-nginx:
    image: nginx:alpine
    container_name: acme-nginx
    ports:
      - "80:80"
    volumes:
      - /opt/acme-https/www:/var/www/certbot:ro
      - ./nginx/acme.conf:/etc/nginx/conf.d/default.conf:ro

  certbot-init:
    image: certbot/certbot:latest
    container_name: certbot-init
    depends_on:
      - acme-nginx
    volumes:
      - /opt/acme-https/www:/var/www/certbot
      - /opt/acme-https/letsencrypt:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "sleep 5 &&
      certbot certonly --webroot --webroot-path=/var/www/certbot \
      --email brucewang5638@gmail.com --agree-tos --no-eff-email \
      -d abacusflow.cn"

  certbot-renew:
    image: certbot/certbot:latest
    container_name: certbot-renew
    volumes:
      - /opt/acme-https/www:/var/www/certbot
      - /opt/acme-https/letsencrypt:/etc/letsencrypt
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do
        certbot renew --webroot --webroot-path=/var/www/certbot --quiet &&
        echo '[renewed] reload nginx...' &&
        docker exec abacusflow-website nginx -s reload;
        docker exec abacusflow-webapp nginx -s reload;
        sleep 12h & wait $${!};
      done"
    restart: unless-stopped


