spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:invenflow}
    username: ${POSTGRES_USER:invenflow}
    password: ${POSTGRES_PASSWORD:123ABCdef*}
    hikari:
      transaction-isolation: TRANSACTION_REPEATABLE_READ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true