-- ✅ 枚举类型定义
create type product_type as enum ('MATERIAL', 'ASSET');
create type product_unit as enum (
    'PIECE', 'BOX', 'PACK', 'DOZEN', 'PAIR', 'GRAM', 'KILOGRAM', 'LITER',
    'MILLILITER', 'METER', 'CENTIMETER', 'BOTTLE', 'BARREL', 'BAG', 'SHEET', 'ROLL', 'ITEM'
    );
create type order_status as enum ('PENDING', 'COMPLETED', 'CANCELED', 'REVERSED');
create type inventory_status as enum ('NORMAL', 'CONSUMED', 'CANCELED', 'REVERSED');
create type inventory_unit_type as enum ('INSTANCE', 'BATCH');
create type user_sex as enum ('M', 'F');

-- ✅ 表结构定义

create table user_account (
                              id bigint generated by default as identity primary key,
                              age integer not null,
                              chars varchar(255),
                              enabled boolean not null,
                              locked boolean not null,
                              name varchar(50) not null constraint uq_user_account_name unique,
                              nick varchar(255),
                              password varchar(255) not null,
                              sex user_sex,
                              created_at timestamp(6) with time zone not null default now(),
                              updated_at timestamp(6) with time zone not null default now()
);
alter table user_account owner to abacusflow;

create table role (
                      id bigint generated by default as identity primary key,
                      label varchar(255),
                      name varchar(50) not null constraint uq_role_name unique,
                      created_at timestamp(6) with time zone not null default now(),
                      updated_at timestamp(6) with time zone not null default now()
);
alter table role owner to abacusflow;

create table user_role (
                           user_id bigint not null constraint fk_user_role_user_id references user_account,
                           role_id bigint not null constraint fk_user_role_role_id references role,
                           primary key (user_id, role_id),
                           created_at timestamp(6) with time zone not null default now(),
                           updated_at timestamp(6) with time zone not null default now()
);
alter table user_role owner to abacusflow;

create table permission (
                            id bigint generated by default as identity primary key,
                            description varchar(255),
                            label varchar(255),
                            name varchar(255),
                            created_at timestamp(6) with time zone not null default now(),
                            updated_at timestamp(6) with time zone not null default now()
);
alter table permission owner to abacusflow;

create table role_permission (
                                 role_id bigint not null constraint fk_role_permission_role_id references role,
                                 permissions_id bigint not null constraint fk_role_permission_permission_id references permission,
                                 primary key (role_id, permissions_id),
                                 created_at timestamp(6) with time zone not null default now(),
                                 updated_at timestamp(6) with time zone not null default now()
);
alter table role_permission owner to abacusflow;

create table product_category (
                                  id bigint generated by default as identity primary key,
                                  description varchar(500),
                                  name varchar(100) not null,
                                  parent_id bigint constraint fk_product_category_parent_id references product_category,
                                  created_at timestamp(6) with time zone not null default now(),
                                  updated_at timestamp(6) with time zone not null default now()
);
alter table product_category owner to abacusflow;

create table product (
                         id bigint generated by default as identity primary key,
                         enabled boolean not null,
                         name varchar(100) not null,
                         note text,
                         specification varchar(50),
                         type product_type,
                         unit product_unit not null,
                         category_id bigint not null constraint fk_product_category_id references product_category,
                         created_at timestamp(6) with time zone not null default now(),
                         updated_at timestamp(6) with time zone not null default now()
);
alter table product owner to abacusflow;

create table inventory (
                           id bigint generated by default as identity primary key,
                           max_stock bigint not null,
                           product_id bigint not null constraint uq_inventory_product_id unique,
                           safety_stock bigint not null,
                           created_at timestamp(6) with time zone not null default now(),
                           updated_at timestamp(6) with time zone not null default now()
);
alter table inventory owner to abacusflow;

create table inventory_unit (
                                id bigint generated by default as identity primary key,
                                unit_type varchar(31) not null,
                                depot_id bigint,
                                purchase_order_id bigint not null,
                                initial_quantity bigint not null,
                                quantity bigint not null,
                                frozen_quantity bigint not null,
                                received_at timestamp(6) with time zone,
                                sale_order_ids bigint[],
                                status inventory_status not null,
                                unit_price numeric(38, 2),
                                version bigint not null,
                                batch_code uuid,
                                serial_number varchar(255),
                                inventory_id bigint constraint fk_inventory_unit_inventory_id references inventory,
                                created_at timestamp(6) with time zone not null default now(),
                                updated_at timestamp(6) with time zone not null default now()
);
alter table inventory_unit owner to abacusflow;


create table purchase_order (
                                id bigint generated by default as identity primary key,
                                no uuid not null constraint uq_purchase_order_no unique,
                                note varchar(255),
                                order_date date,
                                status order_status,
                                supplier_id bigint not null,
                                created_at timestamp(6) with time zone not null default now(),
                                updated_at timestamp(6) with time zone not null default now()
);
alter table purchase_order owner to abacusflow;

create table purchase_order_item (
                                     id bigint generated by default as identity primary key,
                                     product_id bigint not null,
                                     product_type product_type,
                                     quantity integer not null,
                                     serial_number varchar(255),
                                     unit_price numeric(38, 2),
                                     order_id bigint constraint fk_purchase_order_item_order_id references purchase_order,
                                     batch_code uuid,
                                     created_at timestamp(6) with time zone not null default now(),
                                     updated_at timestamp(6) with time zone not null default now()
);
alter table purchase_order_item owner to abacusflow;

create table sale_order (
                            id bigint generated by default as identity primary key,
                            customer_id bigint not null,
                            no uuid not null constraint uq_sale_order_no unique,
                            note varchar(255),
                            order_date date,
                            status order_status,
                            created_at timestamp(6) with time zone not null default now(),
                            updated_at timestamp(6) with time zone not null default now()
);
alter table sale_order owner to abacusflow;

create table sale_order_item (
                                 id bigint generated by default as identity primary key,
                                 inventory_unit_id bigint not null,
                                 inventory_unit_type inventory_unit_type,
                                 quantity integer not null,
                                 unit_price numeric(38, 2),
                                 order_id bigint constraint fk_sale_order_item_order_id references sale_order,
                                 discount_factor numeric(38, 2),
                                 created_at timestamp(6) with time zone not null default now(),
                                 updated_at timestamp(6) with time zone not null default now()
);
alter table sale_order_item owner to abacusflow;

create table customer (
                          id bigint generated by default as identity primary key,
                          address varchar(200),
                          enabled boolean not null,
                          name varchar(100) not null,
                          phone varchar(255),
                          created_at timestamp(6) with time zone not null default now(),
                          updated_at timestamp(6) with time zone not null default now()
);
alter table customer owner to abacusflow;

create table supplier (
                          id bigint generated by default as identity primary key,
                          address varchar(200),
                          contact_person varchar(50),
                          enabled boolean not null,
                          name varchar(100) not null,
                          phone varchar(255),
                          created_at timestamp(6) with time zone not null default now(),
                          updated_at timestamp(6) with time zone not null default now()
);
alter table supplier owner to abacusflow;

create table depot (
                       id bigint generated by default as identity primary key,
                       capacity integer not null,
                       enabled boolean not null,
                       location varchar(200),
                       name varchar(100) not null,
                       created_at timestamp(6) with time zone not null default now(),
                       updated_at timestamp(6) with time zone not null default now()
);
alter table depot owner to abacusflow;

