create table customers
(
    id         bigint generated by default as identity
        primary key,
    address    varchar(200),
    created_at timestamp(6) with time zone,
    enabled    boolean      not null,
    name       varchar(100) not null,
    phone      varchar(255),
    updated_at timestamp(6) with time zone
);

alter table customers
    owner to abacusflow;

create table depots
(
    id         bigint generated by default as identity
        primary key,
    capacity   integer      not null,
    created_at timestamp(6) with time zone,
    enabled    boolean      not null,
    location   varchar(200),
    name       varchar(100) not null,
    updated_at timestamp(6) with time zone
);

alter table depots
    owner to abacusflow;

create table inventories
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) with time zone,
    max_stock    bigint not null,
    product_id   bigint not null
        constraint uk3bms153u88bt0daekfy4qpj6k
            unique,
    safety_stock bigint not null,
    updated_at   timestamp(6) with time zone
);

alter table inventories
    owner to abacusflow;

create table inventory_unit
(
    unit_type          varchar(31)  not null,
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone,
    depot_id           bigint,
    purchase_order_id  bigint       not null,
    initial_quantity   bigint not null,  -- 初始库存
    quantity           bigint not null,  -- 当前库存
    frozen_quantity    bigint not null,  -- 冻结库存
    received_at        timestamp(6) with time zone,
    remaining_quantity bigint       not null,
    sale_order_ids     bigint[],
    status             varchar(255) not null
        constraint inventory_unit_status_check
            check ((status)::text = ANY
                   ((ARRAY ['NORMAL'::character varying, 'CONSUMED'::character varying, 'CANCELED'::character varying, 'REVERSED'::character varying])::text[])),
    unit_price         numeric(38, 2),
    updated_at         timestamp(6) with time zone,
    version            bigint       not null,
    batch_code         uuid,
    serial_number      varchar(255),
    inventory_id       bigint
        constraint fkh7etg40ge99f78dlkniixlpiy
            references inventories
);

alter table inventory_unit
    owner to abacusflow;

create table permissions
(
    id          bigint generated by default as identity
        primary key,
    description varchar(255),
    label       varchar(255),
    name        varchar(255)
);

alter table permissions
    owner to abacusflow;

create table product_categories
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    description varchar(500),
    name        varchar(100) not null,
    updated_at  timestamp(6) with time zone,
    parent_id   bigint
        constraint fknhstaep8s818kydkq4teq8v4e
            references product_categories
);

alter table product_categories
    owner to abacusflow;

create table products
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone,
    enabled       boolean      not null,
    name          varchar(100) not null,
    note          text,
    specification varchar(50),
    type          varchar(255)
        constraint products_type_check
            check ((type)::text = ANY ((ARRAY ['MATERIAL'::character varying, 'ASSET'::character varying])::text[])),
    unit          varchar(255) not null
        constraint products_unit_check
            check ((unit)::text = ANY
                   ((ARRAY ['PIECE'::character varying, 'BOX'::character varying, 'PACK'::character varying, 'DOZEN'::character varying, 'PAIR'::character varying, 'GRAM'::character varying, 'KILOGRAM'::character varying, 'LITER'::character varying, 'MILLILITER'::character varying, 'METER'::character varying, 'CENTIMETER'::character varying, 'BOTTLE'::character varying, 'BARREL'::character varying, 'BAG'::character varying, 'SHEET'::character varying, 'ROLL'::character varying, 'ITEM'::character varying])::text[])),
    updated_at    timestamp(6) with time zone,
    category_id   bigint       not null
        constraint fk6t5dtw6tyo83ywljwohuc6g7k
            references product_categories
);

alter table products
    owner to abacusflow;

create table purchase_orders
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    no          uuid   not null
        constraint uk2whlsdrcaq2mtf79foihcdh3q
            unique,
    note        varchar(255),
    order_date  date,
    status      varchar(255)
        constraint purchase_orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying, 'REVERSED'::character varying])::text[])),
    supplier_id bigint not null,
    updated_at  timestamp(6) with time zone
);

alter table purchase_orders
    owner to abacusflow;

create table purchase_order_items
(
    id            bigint generated by default as identity
        primary key,
    product_id    bigint  not null,
    product_type  varchar(255)
        constraint purchase_order_items_product_type_check
            check ((product_type)::text = ANY
                   ((ARRAY ['MATERIAL'::character varying, 'ASSET'::character varying])::text[])),
    quantity      integer not null,
    serial_number varchar(255),
    unit_price    numeric(38, 2),
    order_id      bigint
        constraint fkdlxkihwo0gv3ygmc02cgos2g4
            references purchase_orders
);

alter table purchase_order_items
    owner to abacusflow;

create table roles
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    label      varchar(255),
    name       varchar(50)                 not null
        constraint ukofx66keruapi6vyqpv6f2or37
            unique,
    updated_at timestamp(6) with time zone not null
);

alter table roles
    owner to abacusflow;

create table roles_permissions
(
    role_id        bigint not null
        constraint fkqi9odri6c1o81vjox54eedwyh
            references roles,
    permissions_id bigint not null
        constraint fk570wuy6sacdnrw8wdqjfh7j0q
            references permissions,
    primary key (role_id, permissions_id)
);

alter table roles_permissions
    owner to abacusflow;

create table sale_orders
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    customer_id bigint not null,
    no          uuid   not null
        constraint uk30gp39esogwq71qtw4fo22cef
            unique,
    note        varchar(255),
    order_date  date,
    status      varchar(255)
        constraint sale_orders_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying, 'REVERSED'::character varying])::text[])),
    updated_at  timestamp(6) with time zone
);

alter table sale_orders
    owner to abacusflow;

create table sale_order_items
(
    id                  bigint generated by default as identity
        primary key,
    inventory_unit_id   bigint  not null,
    inventory_unit_type varchar(255)
        constraint sale_order_items_inventory_unit_type_check
            check ((inventory_unit_type)::text = ANY
                   ((ARRAY ['INSTANCE'::character varying, 'BATCH'::character varying])::text[])),
    quantity            integer not null,
    unit_price          numeric(38, 2),
    order_id            bigint
        constraint fklc6n8ufsct0v8sgd7at7rwgra
            references sale_orders,
    discount_factor     numeric(38, 2)
);

alter table sale_order_items
    owner to abacusflow;

create table suppliers
(
    id             bigint generated by default as identity
        primary key,
    address        varchar(200),
    contact_person varchar(50),
    created_at     timestamp(6) with time zone,
    enabled        boolean      not null,
    name           varchar(100) not null,
    phone          varchar(255),
    updated_at     timestamp(6) with time zone
);

alter table suppliers
    owner to abacusflow;

create table users
(
    id         bigint generated by default as identity
        primary key,
    age        integer                     not null,
    chars      varchar(255),
    created_at timestamp(6) with time zone not null,
    enabled    boolean                     not null,
    locked     boolean                     not null,
    name       varchar(50)                 not null
        constraint uk3g1j96g94xpk3lpxl2qbl985x
            unique,
    nick       varchar(255),
    password   varchar(255)                not null,
    sex        varchar(255)
        constraint users_sex_check
            check ((sex)::text = ANY ((ARRAY ['M'::character varying, 'F'::character varying])::text[])),
    updated_at timestamp(6) with time zone not null
);

alter table users
    owner to abacusflow;

create table users_roles
(
    user_id bigint not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references users,
    role_id bigint not null
        constraint fkj6m8fwv7oqv74fcehir1a9ffy
            references roles,
    primary key (user_id, role_id)
);

alter table users_roles
    owner to abacusflow;

