/* tslint:disable */
/* eslint-disable */
/**
 * abacusflow api
 * 进销存系统服务接口文档
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicUser
 */
export interface BasicUser {
    /**
     * 
     * @type {number}
     * @memberof BasicUser
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof BasicUser
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof BasicUser
     */
    nickname: string;
    /**
     * 
     * @type {number}
     * @memberof BasicUser
     */
    createdAt: number;
}

/**
 * Check if a given object implements the BasicUser interface.
 */
export function instanceOfBasicUser(value: object): value is BasicUser {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BasicUserFromJSON(json: any): BasicUser {
    return BasicUserFromJSONTyped(json, false);
}

export function BasicUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicUser {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'nickname': json['nickname'],
        'createdAt': json['createdAt'],
    };
}

export function BasicUserToJSON(json: any): BasicUser {
    return BasicUserToJSONTyped(json, false);
}

export function BasicUserToJSONTyped(value?: BasicUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'nickname': value['nickname'],
        'createdAt': value['createdAt'],
    };
}

