# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    tags: [ "v*.*.*" ]

  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: abacusflow
  POSTGRES_PASSWORD: abacusflow
  POSTGRES_DB: abacusflow
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/abacusflow/abacusflow-ci:latest
      options: --user root
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        volumes:
          - ${{ github.workspace }}/script/initdb:/docker-entrypoint-initdb.d:ro
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init DB
        uses: ./.github/actions/init-db

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build --no-daemon
          ./gradlew test --no-daemon

      # 保存完整的构建输出和 Gradle 缓存
      - name: Upload build artifacts
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            abacusflow-server/build/
            abacusflow-webapp/build/
            abacusflow-webapp/dist/
            build/
            .gradle/
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: docker.io
      DOCKER_ORG: brucewang5638
      DOCKER_USER: brucewang5638@gmail.com
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          
          # 验证标签格式
          if [[ ! "$TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Tag $TAG 不符合版本规范，应形如 v1.0.0"
            exit 1
          fi
          
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: List files for debugging
        run: |
          ls -la
          ls -la abacusflow-webapp/

      - name: Build Docker images
        run: |
          # 构建 webapp 镜像
          docker build -t "$DOCKER_ORG/abacusflow-webapp:$VERSION" \
          -t "$DOCKER_ORG/abacusflow-webapp:latest" \
          -f abacusflow-webapp/Dockerfile abacusflow-webapp
      
          # 构建 server 镜像
          docker build -t "$DOCKER_ORG/abacusflow-server:$VERSION" \
          -t "$DOCKER_ORG/abacusflow-server:latest" \
          -f abacusflow-server/Dockerfile abacusflow-server

      # docker login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # docker push
      - name: Tag and push Docker images
        run: |
          # Tag and push webapp
          docker tag "abacusflow-webapp:$VERSION" "$DOCKER_ORG/abacusflow-webapp:$VERSION"
          docker tag "abacusflow-webapp:$VERSION" "$DOCKER_ORG/abacusflow-webapp:latest"
          docker push "$DOCKER_ORG/abacusflow-webapp:$VERSION"
          docker push "$DOCKER_ORG/abacusflow-webapp:latest"
          
          # Tag and push server
          docker tag "abacusflow-server:$VERSION" "$DOCKER_ORG/abacusflow-server:$VERSION"
          docker tag "abacusflow-server:$VERSION" "$DOCKER_ORG/abacusflow-server:latest"
          docker push "$DOCKER_ORG/abacusflow-server:$VERSION"
          docker push "$DOCKER_ORG/abacusflow-server:latest"

