# This is a basic CD workflow

name: CD

permissions:
  contents: read
  packages: read

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  DEPLOY_ENVIRONMENT: production

jobs:
  deploy:
    name: Deploy ${{ github.event.release.tag_name }} to ${{ env.DEPLOY_ENVIRONMENT }}
    runs-on: ubuntu-latest
    environment: ${{ env.DEPLOY_ENVIRONMENT }}

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        env:
          # The tag name from the published release
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        with:
          # 从GitHub Secrets中读取服务器连接信息
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          # 在远程服务器上执行的脚本
          script: |
            set -e

            echo "Logging into GitHub Container Registry..."
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.actor }}" --password-stdin

            export ABACUSFLOW_SERVER_VERSION=${{ github.event.release.tag_name }}
            export ABACUSFLOW_WEBAPP_VERSION=${{ github.event.release.tag_name }}

            # 进入项目部署目录
            cd /opt/abacusflow/abacusflow/

            echo "Starting deployment of version ${{ github.event.release.tag_name }} to ${{ env.DEPLOY_ENVIRONMENT }}..."

            if [ "${{ env.DEPLOY_ENVIRONMENT }}" = "production" ]; then
              echo "Using production compose file..."
              docker compose -f docker-compose-prod.yml pull
              docker compose -f docker-compose-prod.yml up -d --remove-orphans
            else
              echo "Error: Unknown environment '${{ env.DEPLOY_ENVIRONMENT }}'"
              exit 1
            fi

            echo "Deployment completed successfully."
