# This is a basic workflow to help you get started with Actions

name: Pull Request CI

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository_owner }}/infra-ci:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -PnoVersion --no-daemon
          ./gradlew test --no-daemon