# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    tags: [ "v*.*.*" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/${{ github.repository_owner }}/infra-ci:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -PnoVersion --no-daemon
          ./gradlew test --no-daemon

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            abacusflow-server/build/
            abacusflow-app/abacusflow-webapp/build/
            abacusflow-app/abacusflow-webapp/dist/
            build/
            .gradle/
          retention-days: 1

  release-webapp-electron:
    if: 1==2 # TODO electron切换为静态文件时再开启
    strategy:
      matrix:
        #        os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: build
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Setup Env
        uses: ./.github/actions/setup-env

      - name: Parse Git Tag
        id: parse-git-tag
        uses: ./.github/actions/parse-git-tag

      - name: Set package.json version
        working-directory: ./abacusflow-app/abacusflow-webapp
        shell: bash
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#v}"
          npm version "$VERSION" --no-git-tag-version --allow-same-version

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew webappBuildElectron --no-daemon

      - name: Release Electron App
        uses: ncipollo/release-action@v1
        with:
          draft: false
          makeLatest: ${{ steps.parse-git-tag.outputs.release_type == 'latest' }}
          prerelease: ${{ steps.parse-git-tag.outputs.release_type == 'pre' }}
          allowUpdates: true
          artifacts: |
            abacusflow-app/abacusflow-webapp/out/linux/*.AppImage
            abacusflow-app/abacusflow-webapp/out/linux/*.deb
            abacusflow-app/abacusflow-webapp/out/linux/*.rpm
            abacusflow-app/abacusflow-webapp/out/linux/*.tar.gz
            abacusflow-app/abacusflow-webapp/out/linux/*.snap
            abacusflow-app/abacusflow-webapp/out/linux/*.pacman
            abacusflow-app/abacusflow-webapp/out/linux/*.freebsd
            abacusflow-app/abacusflow-webapp/out/win32/*.exe
            abacusflow-app/abacusflow-webapp/out/win32/*.msi
            abacusflow-app/abacusflow-webapp/out/win32/*.zip
            abacusflow-app/abacusflow-webapp/out/win32/*.7z
            abacusflow-app/abacusflow-webapp/out/darwin/*.dmg
            abacusflow-app/abacusflow-webapp/out/darwin/*.pkg
            abacusflow-app/abacusflow-webapp/out/darwin/*.zip
            abacusflow-app/abacusflow-webapp/out/darwin/*.app
            abacusflow-app/abacusflow-webapp/out/**/*.blockmap

  release-docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Parse Git Tag
        id: parse-git-tag
        uses: ./.github/actions/parse-git-tag

      # 安装 cosign 用于镜像签名
      - name: Install cosign
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: "v2.2.4"

      # 设置 Docker Buildx 支持多平台构建和缓存
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # 登录到 GitHub Container Registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata for webapp
        id: meta-webapp
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-webapp
          flavor: |
            latest=${{ steps.parse-git-tag.outputs.release_type == 'latest' }}

      - name: Extract Docker metadata for server
        id: meta-server
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-server
          flavor: |
            latest=${{ steps.parse-git-tag.outputs.release_type == 'latest' }}

      - name: Build and push webapp Docker image
        id: build-and-push-webapp
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./abacusflow-app/abacusflow-webapp
          file: ./abacusflow-app/abacusflow-webapp/Dockerfile
          push: true
          tags: ${{ steps.meta-webapp.outputs.tags }}
          labels: ${{ steps.meta-webapp.outputs.labels }}
          cache-from: type=gha,scope=webapp
          cache-to: type=gha,mode=max,scope=webapp
          platforms: linux/amd64,linux/arm64

      - name: Build and push server Docker image
        id: build-and-push-server
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./abacusflow-server
          file: ./abacusflow-server/Dockerfile
          push: true
          tags: ${{ steps.meta-server.outputs.tags }}
          labels: ${{ steps.meta-server.outputs.labels }}
          cache-from: type=gha,scope=server
          cache-to: type=gha,mode=max,scope=server
          platforms: linux/amd64,linux/arm64

      - name: Sign webapp Docker image
        env:
          TAGS: ${{ steps.meta-webapp.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-webapp.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Sign server Docker image
        env:
          TAGS: ${{ steps.meta-server.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-server.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}